[package]
name = "nes_rs"
version = "0.1.0"
authors = ["nathan"]
edition = "2018"

[profile.release] 
debug = true

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
byteorder = "1.4.3"
winit = "0.24.0"
winit_input_helper = "0.9"
pixels = "0.2.0"
rgb = "0.8.27"
clap = "2.33.3"
read_input = "0.8.4"